###########
# CARD DATA  
###########
[Card]
player = "string"
seal = "seal"
is_sentinel = "bool"

[Card.primary]
val = "int"
suit = "suit"

[Card.secondary]
val = "int"
suit = "suit"

[Card.tertiary]
val = "int"
suit = "suit"

[Card.json_tags]
player = "player"
num = "num"

#########
# ENUMS
#########
[Seal]
type = "enum"
values = ["SWAP", "PEEK", "TAX", "WILD", "RESISTANCE", "STATIC", "NONE"]

[Suit]
type = "enum"
values = ["CUTE", "BAD", "MALICOUS"]

############
# Other DATA 
############
[CardCount]
value = "150"
type = "usize"
