[Card]
player = "string"
seal = "seal"
cute = "int"
bad = "int"
malicious = "int"

[Card.json_tags]
player = "player"
suit = "suit"
num = "num"

[Seal]
type = "enum"
values = ["SWAP", "PEEK", "TAX", "WILD", "RESISTANCE", "STATIC", "NONE"]

[Suit]
type = "enum"
values = ["CUTE", "BAD", "MALICOUS"]
