###########
# CARD DATA  
###########
[Card]
player = "string"
seal = "seal"
is_sentinel = "bool"
held = "bool"
id = "usize"

[Card.primary]
val = "int"
suit = "suit"

[Card.secondary]
val = "int"
suit = "suit"

[Card.tertiary]
val = "int"
suit = "suit"

[Card.json_tags]
player = "player"
num = "num"

#########
# ENUMS
#########
[Seal]
type = "enum"
values = ["SWAP", "PEEK", "TAX", "WILD", "RESISTANCE", "STATIC", "NONE"]

[Suit]
type = "enum"
values = ["CUTE", "DUMB", "MALICOUS"]

######################
#SUBMIT HAND STRUCT 
######################
[SubmitHand]
player = "string"
cards = {type = "array", element = "Card", size = 5}

############
# Other DATA 
############
[CardCount]
value = "258"
type = "usize"


