###########
# ENUMS
###########
[Event]
type = "enum"
values = ["res", "tax", "static_conversion"]

###########
# STRUCTS
###########
[SuitFlags]
cute = "bool"
dumb = "bool"
mal = "bool"
played_sentinel = "bool"

[NewEvent]
event = "event"
source = "string"
target = "string"
points = "float"
suit = "suit"

[ResultPlayer]
player = "string"
cute = "float"
dumb = "float"
malicous = "float"
static_pts = "float"
suit_wins = "int"
total = "float"
played_peek = "bool"
played_swap = "bool"
peek_flags = "SuitFlags"

[SubmittedHandsResult]
p1 = "ResultPlayer"
p2 = "ResultPlayer"
events = {type = "slice", element = "NewEvent"}
